### PR TITLE
New Stuff

### PR DESCRIPTION
**Pull request by liv-kami**
Adds pvp tourny sword and new enchant glint

### CODE REVIEW

**Comment by JustAMatt** [comment]
Add the progress on Brews, and remove the demon sword.

**Comment by liv-kami** [comment]
demon sword IS the pvp sword my guy

**Comment by liv-kami** [comment]
Removed pvp sword and added the BEGINNING half of the brew this is **NOT READY FOR RELEASE**

**Comment by liv-kami** [comment]
again, **NOT READY FOR RELEASE**

**Comment by liv-kami** [comment]
and i can help you make it a server resource pack (where it asks ya to use it) once we are at release stage if ya want

**Pull request merged**
